version = 2

[uniform]
command = "/usr/bin/time"
args = ["-v", "cargo", "run", "--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=30"]
regexs = ["(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)", ".*Maximum (resident set size).*: ([0-9.]+)"]

[staged]
command = "cargo"
args = ["run", "--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--stage", "--runtime=30"]
regexs = ["(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)"]

[multiclient]
command = "cargo"
args = ["run", "--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=30", "--getters=8"]
regexs = ["(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)"]

[tx-bank]
command = "cargo"
args = ["run", "--release", "--features", "binaries", "--bin", "bank", "--", "--avg", "--accounts=1000", "--runtime=30", "-t=1"]
regexs = ["(avg PUT): ([0-9.]+)"]

[vote-migration]
command = "cargo"
args = ["run", "--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=60", "--migrate=30"]
regexs = ["(Migration) completed in ([0-9.]+)s"]
lower_better = true
improvement_threshold = 0.5
regression_threshold = 0.5

[post-migration]
command = "cargo"
args = ["run", "--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=30", "--migrate=10"]
regexs = ["avg (GET)\\+: ([0-9.]+)", "avg (PUT)\\+: ([0-9.]+)"]

[slack-aliases]
ms705 = "malte"
fintelia = "jonathan"
omegablitz = "aashish"
rtmrtmrtmrtm = "rtm"
larat7 = "laratimbo"
jmftrindade = "jmf"
