[uniform]
command = "run"
args = ["--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=30"]
regexs = ["(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)"]

[staged]
command = "run"
args = ["--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--stage", "--runtime=30"]
regexs = ["(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)"]

[multiclient]
command = "run"
args = ["--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=30", "--getters=8"]
regexs = ["(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)"]

[tx-bank]
command = "run"
args = ["--release", "--features", "binaries", "--bin", "bank", "--", "--avg", "--accounts=5", "--runtime=30"]
regexs = ["(avg PUT): ([0-9.]+)"]

[vote-migration]
command = "run"
args = ["--release", "--features", "binaries", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=60", "--migrate=30"]
regexs = ["(Migration) completed in ([0-9.]+)s"]
lower_better = true

[slack-aliases]
ms705 = "malte"
fintelia = "jonathan"
omegablitz = "aashish"
rtmrtmrtmrtm = "rtm"
larat7 = "laratimbo"
jmftrindade = "jmf"
