[vote-uniform]
command = "run"
args = ["--bin", "vote", "--", "--distribution=uniform", "--articles=100000", "--runtime=70", "soup://"]
regexs = ["60[0-9]{9} (GET[0-9]+: [0-9.]+)", "60[0-9]{9} (PUT: [0-9.]+)"]

[vote-zipf]
command = "run"
args = ["--bin", "vote", "--", "--distribution=zipf", "--articles=100000", "--runtime=70", "soup://"]
regexs = ["60[0-9]{9} (GET[0-9]+: [0-9.]+)", "60[0-9]{9} (PUT: [0-9.]+)"]
